name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: Setup UPX
        run: |
          sudo apt install upx -y

      - name: Build
        run: CGO_ENABLED=0 go build -v -ldflags="-s -w"

      - name: Pack with UPX
        run: |
          Origina Size=$(ls -lah | grep tf2-rcon | awk '{print $5}')
          upx --best -o packed_binary tf2-rcon
          mv packed_binary tf2-rcon
          Packed Size=$(ls -lah | grep tf2-rcon | awk '{print $5}')
