name: SLSA go releaser
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  # Generate ldflags dynamically.
  # Optional: only needed for ldflags.
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
      major: ${{ steps.major.outputs.major }}
      minor: ${{ steps.minor.outputs.minor }}
      patch: ${{ steps.patch.outputs.patch }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"
          echo "major=$(git describe --tags --always --dirty | cut -d '.' -f1 | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "minor=$(git describe --tags --always --dirty | cut -d '.' -f2)" >> "$GITHUB_OUTPUT"
          echo "patch=$(git describe --tags --always --dirty | cut -d '.' -f3 | cut -d '-' -f1 | cut -d '+' -f1)" >> "$GITHUB_OUTPUT"

  # Trusted builder.

  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    needs: args
    strategy:
      matrix:
        os:
          - linux
          - windows
          - darwin
        arch:
          - amd64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.5.0
    with:
      go-version: 1.18.3
      config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml
      # Optional: only needed if using ldflags.
      evaluated-envs: 'COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}, MAJOR:${{needs.args.outputs.major}}, MINOR:${{needs.args.outputs.minor}}, PATCH:${{needs.args.outputs.patch}}'
      upload-assets: true
      # upload-tag-name: ${{ github.ref }}
